feat: install extensions

diff --git a/pack/gnome b/pack/gnome
--- a/pack/gnome
+++ b/pack/gnome
@@ -1,5 +1,34 @@
 #!/usr/bin/env bash
 
+install_extension() {
+    local uuid="$1"
+    local major
+    local version
+    local tmpfile
+
+    major=$(gnome-shell --version | awk '{print $3}' | cut -d. -f1)
+    # tmpfile=$(mktemp /tmp/$uuid.zip)
+    tmpfile=$(mktemp /tmp/gnome-ext.XXXXXX.zip)
+
+    version=$(wget -qO- "https://extensions.gnome.org/api/v1/extensions/${uuid}/versions?page=1&page_size=100" \
+        | jq ".results | map(select(.shell_versions[].major == ${major})) | max_by(.version).version")
+
+    if [[ -z "$version" || "$version" == "null" ]]; then
+        echo "No compatible version found for GNOME $major"
+        return 1
+    fi
+
+    wget -qO "$tmpfile" "https://extensions.gnome.org/api/v1/extensions/$uuid/versions/$version/?format=zip" || {
+        echo "Download failed"
+        return 1
+    }
+
+    echo "Installing $uuid version $version"
+    gnome-extensions install --force "$tmpfile"
+
+    rm -f "$tmpfile"
+}
+
 find_terminal() {
   for t in ghostty wezterm:org.wezfurlong.wezterm ptyxis; do
     local b f
@@ -89,6 +118,8 @@ gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 
 gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'suspend'
 gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout 300
 
+# -----------------------------------------------------------------------------
+
 echo "Installing GNOME Extensions..."
 
 # install pop-shell (pop-shell@system76.com)
@@ -108,3 +139,16 @@ if gnome-extensions info pop-shell@system76.com >/dev/null 2>&1; then
     gsettings set org.gnome.shell.extensions.pop-shell stacking-with-mouse false
 fi
 
+install_extension 'blur-my-shell@aunetx'
+install_extension 'caffeine@patapon.info'
+install_extension 'Vitals@CoreCoding.com'
+install_extension 'drive-menu@gnome-shell-extensions.gcampax.github.com'
+install_extension 'just-perfection-desktop@just-perfection'
+install_extension 'space-bar@luchrioh'
+install_extension 'auto-move-windows@gnome-shell-extensions.gcampax.github.com'
+
+echo -e "Installation complete\n"
+echo "Login again or reboot to enable installed extensions"
+
+#set this in justfile
+#gnome-extensions enable "$uuid"
